import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { theme } from "@/theme";
import { MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { Notifications } from "@mantine/notifications";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <Notifications />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
